/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/achievements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List visible achievements */
        get: operations["listAchievements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim all eligible achievements for an account */
        post: operations["claimAchievements"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AchievementMetadata: {
            /** @example wager-warrior-100k */
            id: string;
            /** @example Wager Warrior - 100K */
            name: string;
            /** @example Reach a total wagered amount of 100K USD equivalent. */
            description: string;
            /** Format: uri */
            imageUrl?: string | null;
            display?: {
                /** @enum {string} */
                category?: "wagering" | "wins" | "losses" | "loyalty" | "lp" | "community" | "game";
                /** @example Wager Warrior */
                series?: string;
                /** @example wager_warrior */
                seriesKey?: string;
                /** @example 1 */
                tier?: number;
                /** @example 6 */
                tiersTotal?: number;
                /** @example 1 */
                order?: number;
                /** @example [
                 *       "milestone",
                 *       "volume"
                 *     ] */
                tags?: string[];
                scope?: {
                    /**
                     * @example global
                     * @enum {string}
                     */
                    kind?: "global" | "game";
                    /** @example xplosion */
                    gameKey?: string | null;
                    /** @example Xplosion Slots */
                    gameName?: string | null;
                } | null;
            } | null;
        };
        ClaimRequest: {
            /** @description Voi (Algorand) address */
            account: string;
        };
        ClaimResult: {
            minted: {
                /** @example wager-warrior-100k */
                id: string;
                /** @example SOMEALGOTXNID... */
                txnId: string;
            }[];
            errors: {
                id: string;
                /** @example Already minted */
                reason: string;
            }[];
        };
        Error: {
            /** @example Invalid account */
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAchievements: {
        parameters: {
            query?: {
                account?: string;
                category?: "wagering" | "wins" | "losses" | "loyalty" | "lp" | "community" | "game";
                seriesKey?: string;
                game?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of public (and account-visible) achievements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AchievementMetadata"][];
                };
            };
            /** @description Invalid account */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    claimAchievements: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClaimRequest"];
            };
        };
        responses: {
            /** @description Mint results per achievement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimResult"];
                };
            };
            /** @description Invalid account */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
